config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    root to: "homes#top"
  end

  scope module: :public do
    resources :items, only: [:index, :show]
      get "customers/unsubscribe" => "customers#unsubscribe"
      patch "customers/withdraw" => "customers#withdraw"
      get "customers/my_page" => "customers#show"
      get "customers/infomation/edit" => "customers#edit"
      patch "customers/infomation" => "customers#update"
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete "destroy_all" => "cart_items#destroy_all"
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get "thanks" => "orders#thanks"
        post "confirm" => "orders#confirm"
      end
    end
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    root to: "homes#top"
    get "about" => "homes#about"
  end


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  has_many :orders, through: :order_details

  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    # image.variant(resize_to_limit: [width, height]).processed
    image.variant(gravity: :center, resize:"#{width}x#{height}^", crop:"#{width}x#{height}+0+0").processed
  end

  def add_tax_price
    (self.price * 1.10).round
  end

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3 px-sm-0 offset-sm-1">
      <h2>商品編集</h2>
    </div>

    <div class="col-md-6 offset-md-3">
      <%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>
      <table class="table">
        <tr>
          <th style="border:none;">商品画像</th>
          <td style="border:none;"><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr>
          <th style="border:none;">商品名</th>
          <td style="border:none;"><%= f.text_field :name, size: "30x20" %></td>
        </tr>
        <tr>
          <th style="border:none;">商品説明</th>
          <td style="border:none;"><%= f.text_area :introduction, size: "30x5" %></td>
        </tr>
        <tr>
          <th style="border:none;">ジャンル</th>
          <td style="border:none;"><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), size: "30x20" %></td>
        </tr>
        <tr>
          <th style="border:none;">税抜価格</th>
          <td style="border:none;"><%= f.text_field :price, size: "30x20" %> 円</td>
        </tr>
        <tr>
          <th style="border:none;">販売ステータス</th>
          <td style="border:none;">
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中" %>
          </td>
        </tr>
      </table>
      <div class="col d-flex justify-content-center">
         <%= f.submit "変更を保存", class: "btn btn-success btn-lg mx-auto" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2>商品一覧</h2>
    </div>
    <div>
      <%= link_to new_admin_item_path do %>
        <i class="fa-solid fa-circle-plus"></i>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <table class="table text-center mb-5">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td>
                <%= item.id %>
              </td>
              <td>
                <%= link_to admin_item_path(item.id) do %>
                  <%= item.name %>
                <% end %>
              </td>
              <td>
                <%= item.price.to_s(:delimited) %>
              </td>
              <td>
                <%= item.genre.name %>
              </td>
              <td>
                <% if item.is_active == true %>
                  <label class="text-success">販売中</label>
                <% else %>
                  <label class="text-danger">販売停止中</label>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="col d-flex justify-content-center">
        <%= paginate @items %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3 px-sm-0 offset-sm-1">
      <h2>商品新規登録</h2>
    </div>

    <div class="col-md-6 offset-md-3 ">
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
        <table class="table">
          <tr>
            <th style="border:none;"><%= f.label :商品画像 %></th>
            <th style="border:none;"><%= f.file_field :image, accept: "image/*" %></th>
          </tr>
          <tr>
            <th style="border:none;"><%= f.label :商品名 %></th>
            <td style="border:none;"><%= f.text_field :name, placeholder: "商品名", size: "30x20" %></td>
          </tr>
          <tr>
            <th style="border:none;"><%= f.label :商品説明 %></th>
            <td style="border:none;"><%= f.text_area :introduction, size: "30x5", placeholder: "ここに説明文を記述します" %></td>
          </tr>
          <tr>
            <th style="border:none;"><%= f.label :ジャンル %></th>
            <td style="border:none;"><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), class: "30x20" %></td>
          </tr>
          <tr>
            <th style="border:none;"><%= f.label :税抜価格 %></th>
            <td style="border:none;"><%= f.text_field :price, placeholder: "1000", size: "30x20" %> 円</td>
          </tr>
          <tr>
            <th style="border:none;"><%= f.label :販売ステータス %></th>
            <td style="border:none;">
              <%= f.radio_button :is_active, true %>
              <%= f.label :is_active, "販売中" %>
              <%= f.radio_button :is_active, false %>
              <%= f.label :is_active, "販売停止中", {value: :false, style: "display: inline-block;"} %>
            </td>
          </tr>
        </table>
        <div class="col d-flex justify-content-center">
          <%= f.submit "新規登録", class: "btn btn-success btn-lg mx-auto" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <h2>商品詳細</h2>
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @item.get_image(400,250) %>
    </div>
    <div class="col-md-7 offset-md-1">
      <table class="table">
        <tr>
          <th style="border:none;">商品名</th>
          <td style="border:none;"><%= @item.name %></td>
        </tr>
        <tr>
          <th style="border:none;">商品説明</th>
          <td style="border:none;"><%= @item.introduction %></td>
        </tr>
        <tr>
          <th style="border:none;">ジャンル</th>
          <td style="border:none;"><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th style="border:none;">税込価格</th>
          <td style="border:none;"><%= @item.add_tax_price.to_s(:delimited) %>
              (<%= @item.price.to_s(:delimited) %>) 円
          </td>
        </tr>
        <tr>
          <th style="border:none;">販売ステータス</th>
          <td style="border:none;">
            <% if @item.is_active == true  %>
              <span class="text-success">販売中</span>
            <% else %>
              <span class="text-danger">販売停止中</span>
            <% end %>
          </td>
        </tr>
        <tr>
          <th style="border:none;">
            <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success btn-lg mx-auto" %>
          </th>
        </tr>
      </table>
    </div>
  </div>
</div>