config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    root to: "homes#top"
  end

  scope module: :public do
    resources :items, only: [:index, :show]
      get "customers/unsubscribe" => "customers#unsubscribe"
      patch "customers/withdraw" => "customers#withdraw"
      get "customers/my_page" => "customers#show"
      get "customers/infomation/edit" => "customers#edit"
      patch "customers/infomation" => "customers#update"
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete "destroy_all" => "cart_items#destroy_all"
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get "thanks" => "orders#thanks"
        post "confirm" => "orders#confirm"
      end
    end
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    root to: "homes#top"
    get "about" => "homes#about"
  end


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == true)
  end

  def full_name
    self.last_name + "" + self.first_name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h4 class="title"><strong><%= @customer.full_name %>さんの会員情報編集</strong></h4>
  <div class="row">
    <div class="col-10">
      <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
        <div class="field row">
          <label class="col-3">会員ID</label>
          <p class="col-1"><%= @customer.id %></p>
        </div>

        <div class="field row">
          <label for="inputName" class=" col-3 col-form-label">氏名</label>
          <div class="col-3">
            <%= f.text_field :last_name, class:"form_control", id:'inputName' %>
          </div>
          <div class="col-3">
            <%= f.text_field :first_name, class:"form_control", id:'inputName' %>
          </div>
        </div>

        <div class="field row">
          <label for="inputNameKana" class="col-3 col-form-label">フリガナ</label>
          <div class="col-3">
            <%= f.text_field :last_name_kana, class:"form_control", id:'inputName' %>
          </div>
          <div class="col-3">
            <%= f.text_field :first_name_kana, class:"form_control", id:'inputName' %>
          </div>
        </div>

        <div class="field row">
          <label for="inputPostal_code" class="col-3 col-form-label">郵便番号</label>
          <div class="col-3">
            <%= f.text_field :postal_code, class:"form_control", id:'inputPostal_code' %>
          </div>
        </div>

        <div class="field row">
          <label for="inputAddress" class="col-3 col-form-label">住所</label>
          <div class="col-3">
            <%= f.text_field :address, class:"form_control size-input-address", id:'inputAddress' %>
          </div>
        </div>

        <div class="field row">
          <label for="inputTelephone_number" class="col-3 col-form-label">電話番号</label>
          <div class="col-3">
            <%= f.text_field :telephone_number, class:"form_control", id:'inputTelephone_number' %>
          </div>
        </div>

        <div class="field row">
          <label for="inputEmail" class="col-3 col-form-label">メールアドレス</label>
          <div class="col-3">
            <%= f.email_field :email, class:"form_control", id:'inputEmail' %>
          </div>
        </div>

        <div class="field row">
          <label for="inputStatus" class="col-3 col-form-label">会員ステータス</label>
          <div class="col-3">
            <%= f.radio_button :is_active, true, id:'inputStatusTrue' %>
            <label for="inputStatusTrue" class="col-form-label">有効</label>
            <%= f.radio_button :is_active, false, id:'inputStatueFalse' %>
            <label for="inputStatusFalse" class="col-form-label">退会</label>
          </div>
        </div>

        <div class="col-3">
          <%= f.submit "変更を保存", class:"btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class = "container">
  <div class = "row">
    <div class "col-md-4 px-sm-0 mx-auto ">
      <h2>会員一覧</h2>
    </div>
    <div class = "col-md-7 offset-md-1 mt-5 pt-2 ">
      <table class = "table  ">
        <thead>
          <tr>
            <th class = "table-active">会員ID</th>
            <th class = "table-active">氏名</th>
            <th class = "table-active">メールアドレス</th>
            <th class = "table-active">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers .each do |customers| %>
          <tr>
            <td ><%= customers.id %></td>
            <td >
              <%= link_to admin_customer_path(customers.id) do %>
              <%= customers.last_name %>
              <%= customers.first_name %>
              <% end %>
            </td>
            <td ><%= customers.email %></td>
            <td >
              <% if customers.is_deleted %>
                <p class="text-success"><strong>有効</strong></p>
              <% else %>
                <p class="text-danger"><strong>退会</strong></p>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="col d-flex justify-content-center" >
      <%= paginate @customers %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <h4 class="title bg-light"><strong><%= @customer.full_name %>さんの会員詳細</strong></h4>
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= @customer.last_name %><%= @customer.first_name %></td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td>
              <% if @customer.is_deleted %>
                <p class="text-success"><strong>有効</strong></p>
              <% else %>
                <p class="text-danger"><strong>退会</strong></p>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-2 offset-2">
      <%= link_to "編集する", edit_admin_customer_path, class:'btn btn-success px-3' %>
    </div>
    <div class="col-3">
      <%=link_to "注文履歴一覧を見る", admin_root_path, class:'btn btn-primary px-3' %>
    </div>
  </div>
</div>