config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    root to: "homes#top"
  end

  scope module: :public do
    resources :items, only: [:index, :show]
      get "customers/unsubscribe" => "customers#unsubscribe"
      patch "customers/withdraw" => "customers#withdraw"
      get "customers/my_page" => "customers#show"
      get "customers/infomation/edit" => "customers#edit"
      patch "customers/infomation" => "customers#update"
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete "destroy_all" => "cart_items#destroy_all"
      end
    end
    resources :orders, only: [:new, :create, :index, :show] do
      collection do
        get "thanks" => "orders#thanks"
        post "confirm" => "orders#confirm"
      end
    end
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    root to: "homes#top"
    get "about" => "homes#about"
  end


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  with_options presence: do
    validates :payment_method
    validates :total_payment
    validates :shipping_cost
    validates :postal_code
    validates :address
    validates :name
    validates :status
  end

  enum payment_method: { credit_card: 0, transfer: 1}
  # 入金待ち0, 入金確認1, 製作中2, 発送準備中3, 発送済み4
  enum status: {wait_for_payment: 0, payment_confirmation: 1, in_making: 2, preparing_delivery: 3, delivered: 4}

  def postal_code_and_address_and_name
    "〒#{self.postal_code} #{self.address}\n#{self.name}"
  end

  def add_tax_price
    (self.price * 1.10).round
  end

  def subtotal # 小計
    self.add_tax_price * self.amount
  end

  def total_paymen_sum
    self.total_payment + self.shipping_cost
  end

  def total_item_amount #合計金額
   order_details.sum { |order_detail| order_detail.subtotal }
  end
  # ブロック変数 => 繰り返すときに使用。
  #order_detailsに紐づくすべてのアイテム合計金額を出したいのでブロック変数使用。
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_status = @order.status
    @order_details = OrderDetail.where(order_id: @order.id)
    
  end

  def update
    order = Order.find(params[:id])
    order.status = params[:order][:status]
    if order.status == "payment_confirmation"
      order.order_details.each do |detail|
        detail.update(making_status: 1)
      end
    end
    if order.update(order_params)
      redirect_to admin_order_path(order)
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :total_payment, :payment_method, :posal_code, :addrss, :status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <h4 class="title"><strong>注文履歴詳細</strong></h4>
  <div class="row">
    <div class="col-10">
      <table class="table table-borderless">
        <thead>
          <tr>
            <th>購入者</th>
            <td><%= link_to @order.name, admin_customers_path %></td>
          </tr>

          <tr>
            <th>注文日</th>
            <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
          </tr>

          <tr>
            <th>配送先</th>
            <td><%= (@order.postal_code_and_address_and_name) %></td>
          </tr>

          <tr>
            <th>支払方法</th>
            <td><%= @order.payment_method_i18n %></td>
          </tr>

          <tr>
            <th>注文ステータス</th>
            <td>
              <%= form_with model: @order, url: admin_order_path(@order) do |f| %>
                <%= f.select :status, (0..4).to_a.map{ |q| ["#{ I18n.t("enums.order.status.#{Order.statuses.key(q)}")}",Order.statuses.key(q)] }, { selected: @order.status } %>
                <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
        </thead>
      </table>
    </div>

    <div class="col-9">
      <table class="table table-bordered">
        <thead>
          <tr class="bg-light">
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <body>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.add_tax_price.to_s(:delimited) %></td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.subtotal.to_s(:delimited) %></td>
            <td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail) do |f| %>
                <%= f.select :making_status, (0..3).to_a.map{ |q| ["#{ I18n.t("enums.order_detail.making_status.#{OrderDetail.making_statuses.key(q)}")}",OrderDetail.making_statuses.key(q)] }, { selected: order_detail.making_status } %>
                <%= f.submit "更新", class:"btn btn-success" %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </body>
      <table>
    </div>

    <div class"col-4">
      <table>
        <thead>
          <tr>
            <th>商品合計</th>
            <td><%= @order.total_payment.to_s(:delimited) %>円</td>
          </tr>

          <tr>
            <th>送料</th>
            <td><%= @order.shipping_cost.to_s(:delimited) %>円</td>
          </tr>

          <tr>
            <th>請求合計</th>
            <td><%= @order.total_paymen_sum.to_s(:delimited) %>円</td>
          </tr>
        </thead>
      </table>
    </div>
  </div>
</div>